### ISSUE TITLE
uxml.writer not escaping attribute cdata?

### ISSUE THREAD

**Issue by distobj** [uogbuji/amara3-xml#19]
I wrote some code using amara3.uxml to modify MARCXML records. I thought I'd be able to use a xmlter.sender coroutine for input and write it out with uxml.writer losslessly. That's not happening though, when it encounters character references on input, specifically the quot character reference in this case, it gets turned into a quote character, producing non-well-formed output.

Here's a [script](https://github.com/uogbuji/amara3-xml/files/5882697/marcxmlcopy.txt) and some [input data](https://github.com/uogbuji/amara3-xml/files/5882701/quoteattr.txt) to reproduce

**Comment by uogbuji** [comment]
@distobj I heard via backchannel that you need an urgent fix? I had not been made aware of that. The above commit on this hotfix branch seems to work with your example, but is not fully tested. It will take a fair bit more effort before it is, in order to make sure we're finally developing in a mature manner. But if it's a blocker, you can ry cherry-picking this patch to see if it gets you over the hump.

**Comment by uogbuji** [comment]
Quick update on this. Working on turning the sample files into a test case I ran into a problem with & /. &amp; double-escaping. Hoping to have a hotfix as soon as I can track that down, then a release today, or at least before Monday.

**Comment by uogbuji** [comment]
OK fixed, tested & [released](https://pypi.org/project/amara3.xml/).
